# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'wakatime' # See documentation for possible values
      interval_count: 1 # Number of intervals before the next update
      start_time: '00:00' # Time of day to start the update
      timezone: 'UTC' # Timezone of the start_time
      weekday: 'monday' # Day of the week to start the update
      weekday_offset: 0 # Number of days to offset the weekday

  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'wakatime' # See documentation for possible values
      interval_count: 1 # Number of intervals before the next update
      start_time: '00:00' # Time of day to start the update
      timezone: 'UTC' # Timezone of the start_time
      weekday: 'tuesday' # Day of the week to start the update
      weekday_offset: 0 # Number of days to offset the weekday_offset

  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'wakatime' # See documentation for possible values
      interval_count: 1 # Number of intervals before the next update
      start_time: '00:00' # Time of day to start the update
      timezone: 'UTC' # Timezone of the start_time
      weekday: 'wednesday' # Day of the week to start the update
